<?php
    class Account{

        // properties, Attributes, Fields

        //   private $id;  // kendi klasım erişebiliyor
        //   public $name; // herkes tarafından erişibeliyor
        //   protected $balance; // dışardan erişim sağlayamıyoruz ama miras alırsa erişim sağlayabilir


        private $id = 1;
        private $name = "Ömer Faruk";
        private $balance = 1000;

        // Methods

        public function  __construct($id,$name,$balance)
        {
            $this->id = $id;
            $this->name = $name;
            $this->balance = $balance;


        }

        public  function getName(){
            return $this->name;
        }

        public  function getId(){
            return $this->id;
        }


        public  function getBalance(){
            return $this->balance;
        }

        public function  showInfos(){

            echo "Bilgiler <br>";
            echo "Id:$this->id <br>";
            echo "İsim:$this->name <br>";
            echo "Vadesiz Bakiye:$this->balance<br>";

        }


    }

    class SpecialAcount extends Account {

        private $interest;

        public function __construct($id, $name, $balance,$interest)
        {
            parent::__construct($id, $name, $balance);
            $this->interest = $interest;
        }

        public function  getInterest(){
            return $this->interest;
        }
        // Override

        public function showInfos()
        {
            parent::showInfos(); // TODO: Change the autogenerated stub
            echo "İntresti : $this->interest";
        }

    }

    $specialAccount1 = new SpecialAcount(1,"Ömer Faruk",156, "Manager");
    echo $specialAccount1->getName();
    echo $specialAccount1->getBalance();

    echo $specialAccount1->getInterest();
    $specialAccount1->showInfos();



//    // $account1 = new Account(); // yeni obje oluşturdum
//    $account2 = new Account(12,"Faruk karadelen", 2698);
//    $account3 = new Account(35,"Yakup odayabakan", 564);
//
//    // classımızdaki elemanlar public olduğundan bu şekilde erişim sağlayabiliriz
//    /*
//    echo $account1->id;
//    print($account1->name);
//    echo $account1->balance;
//    */
//
//    // özellikler private olduğunda getter larla bilgi çekebiliriz
//
//        // echo $account1->getId();
//        // print($account1->getName());
//        // echo $account1->getBalance();
//
//    // bütün bilgileri tek seferde çekmek için function kullanabiliriz (private/public farketmez)
//       // $account1->showInfos();
//       // $account2->showInfos();
//
////    $account2->showInfos();  echo "<hr>";$account3->showInfos();

?>
